"use client";
import { useState, type FormEvent } from "react";
import { Search } from "lucide-react";
import { money } from "@/lib/money";
type TrackedOrder = { orderNumber: string; status: string; paymentStatus: string; paymentMethod: string; totalAmount: string | number; createdAt: string; items: Array<{ productName: string; variantLabel: string; quantity: number; lineTotal: string | number }> };
export default function OrdersPage() {
  const [number, setNumber] = useState(""); const [phone, setPhone] = useState(""); const [order, setOrder] = useState<TrackedOrder | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function lookup(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setOrder(null); const response = await fetch(`/api/orders/${encodeURIComponent(number.trim())}?phone=${encodeURIComponent(phone.trim())}`); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(data.error || "Order not found."); return; } setOrder(data); }
  return <main className="container"><div className="page-top"><div className="eyebrow" style={{ color: "#64836b" }}>Order tracking</div><h1>Where’s my order?</h1><p>Enter the order number and phone used at checkout.</p><form className="search-row" onSubmit={lookup}><label className="field"><span>Order number</span><input className="input" required value={number} onChange={(event) => setNumber(event.target.value)} placeholder="SH-2026-ABC123"/></label><label className="field"><span>Phone number</span><input className="input" required value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Phone used at checkout"/></label><button className="button" type="submit" disabled={busy}><Search size={15}/>{busy ? "Looking…" : "Find order"}</button></form></div>{error && <div className="notice error">{error}</div>}{order && <section className="tracking-card"><div className="section-head"><div><span className="status-pill">{order.status.replaceAll("_", " ")}</span><h2>{order.orderNumber}</h2></div><strong>{money(order.totalAmount)}</strong></div><p className="tax-hint">Placed {new Date(order.createdAt).toLocaleString("en-IN")} · Payment {order.paymentStatus.toLowerCase()} · {order.paymentMethod.replaceAll("_", " ").toLowerCase()}</p>{order.items.map((item, index) => <div className="summary-line" key={index}><span>{item.quantity} × {item.productName} ({item.variantLabel})</span><strong>{money(item.lineTotal)}</strong></div>)}<div className="notice">The store team will contact you to confirm your order and handover details.</div></section>}<div style={{ marginBottom: 65 }}/></main>;
}
