"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Printer } from "lucide-react";
import { money } from "@/lib/money";

type DocumentItem = { productName: string; variantLabel: string; sku: string; quantity: number; quotedPrice?: string | number; unitPrice?: string | number; gstRate: string | number; lineTotal?: string | number };
type DocumentData = { id: string; quoteNumber?: string; invoiceNumber?: string; createdAt?: string; orderDate?: string; paymentDueDate?: string; status?: string; paymentStatus?: string; school: { name: string; contactPerson: string; phone: string; address: string }; items: DocumentItem[] };
type Store = { legalName: string; address: string; phone: string; gstin: string };

export default function AdminDocumentPage({ params }: { params: Promise<{ kind: string; id: string }> }) {
  const { kind, id } = use(params);
  const [result, setResult] = useState<{ kind: string; document: DocumentData; store: Store } | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/admin/documents/${kind}/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Document could not be loaded."); return data; }).then(setResult).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Document could not be loaded.")); }, [kind, id]);
  if (error) return <main className="container page-top"><Link className="small-button" href="/admin"><ArrowLeft size={14}/> Store desk</Link><div className="notice error">{error}</div></main>;
  if (!result) return <main className="container loading">Loading document…</main>;
  const { document, store } = result;
  const isInvoice = result.kind === "invoice";
  const grandTotal = document.items.reduce((sum, item) => sum + Number(item.lineTotal ?? (item.quotedPrice ?? item.unitPrice ?? 0) as string | number), 0);
  const tax = document.items.reduce((sum, item) => { const price = Number(item.quotedPrice ?? item.unitPrice ?? 0); return sum + price * item.quantity * Number(item.gstRate) / (100 + Number(item.gstRate)); }, 0);
  return <main className="container document-wrap"><div className="document-toolbar"><Link className="small-button" href="/admin"><ArrowLeft size={14}/> Store desk</Link><button className="button" onClick={() => window.print()}><Printer size={15}/> Print / Save PDF</button></div><article className="paper-document"><header className="document-brand"><div><div className="eyebrow" style={{ color: "#64836b" }}>Selection House</div><h1>{store.legalName}</h1><p>{store.address}{store.phone && <><br/>Phone: {store.phone}</>}{store.gstin && <><br/>GSTIN: {store.gstin}</>}</p></div><div className="document-kind"><div>{isInvoice ? store.gstin ? "GST INVOICE" : "GST INVOICE DRAFT · GSTIN REQUIRED" : "QUOTATION"}</div><strong>{isInvoice ? document.invoiceNumber : document.quoteNumber}</strong><small>{new Date(document.orderDate || document.createdAt || "1970-01-01").toLocaleDateString("en-IN")}</small></div></header>{isInvoice && !store.gstin && <div className="notice error">Enter STORE_GSTIN in the deployment environment before issuing this draft as a tax invoice.</div>}<section className="document-recipient"><div><small>Bill to</small><strong>{document.school.name}</strong><span>{document.school.contactPerson} · {document.school.phone}</span>{document.school.address && <span>{document.school.address}</span>}</div>{isInvoice && <div className="document-due"><small>Payment due</small><strong>{new Date(document.paymentDueDate!).toLocaleDateString("en-IN")}</strong><span>{document.paymentStatus}</span></div>}</section><table className="document-table"><thead><tr><th>#</th><th>Item description</th><th>SKU</th><th>Qty</th><th>Rate incl. GST</th><th>GST</th><th>Amount</th></tr></thead><tbody>{document.items.map((item, index) => { const price = Number(item.quotedPrice ?? item.unitPrice ?? 0); const line = Number(item.lineTotal ?? price * item.quantity); return <tr key={`${item.sku}-${index}`}><td>{index + 1}</td><td><strong>{item.productName}</strong><small>{item.variantLabel}</small></td><td>{item.sku}</td><td>{item.quantity}</td><td>{money(price)}</td><td>{Number(item.gstRate)}%</td><td>{money(line)}</td></tr>; })}</tbody></table><section className="document-totals"><div><span>Tax included in prices</span><strong>{money(tax)}</strong></div><div className="document-grand"><span>{isInvoice ? "Invoice total" : "Quotation total"}</span><strong>{money(grandTotal)}</strong></div></section><footer className="document-footer"><div><strong>{isInvoice ? "Payment terms" : "Quotation notes"}</strong><p>{isInvoice ? `Please arrange payment by ${new Date(document.paymentDueDate!).toLocaleDateString("en-IN")}.` : "Prices include GST at the product rates shown. Stock is subject to confirmation when this quotation is accepted."}</p><p>No formal purchase order or challan is required for this school order.</p></div><div className="signature"><span>For {store.legalName}</span><div/><small>Authorized signatory</small></div></footer></article></main>;
}
