"use client";
import Link from "next/link";
import { ArrowRight, Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { money } from "@/lib/money";
export default function CartPage() {
  const { items, subtotal, setQuantity, remove } = useCart();
  return <main className="container"><div className="page-top"><div className="eyebrow" style={{ color: "#64836b" }}>Your selection</div><h1>Shopping bag</h1><p>Stock is confirmed when you place your order.</p></div>{!items.length ? <div className="empty-state" style={{ marginBottom: 65 }}><h2>Your bag is waiting for game day.</h2><p>Pick a sport and find the gear you need.</p><Link className="button" href="/">Browse the collection <ArrowRight size={15}/></Link></div> : <div className="cart-layout"><section className="cart-lines">{items.map((item) => <div className="cart-line" key={item.variantId}><div><strong>{item.productName}</strong><div className="product-brand" style={{ marginTop: 6 }}>{item.variantLabel} · SKU {item.sku}</div></div><div className="quantity-control"><button onClick={() => setQuantity(item.variantId, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={12}/></button><span>{item.quantity}</span><button onClick={() => setQuantity(item.variantId, item.quantity + 1)} aria-label="Increase quantity" disabled={item.quantity >= item.stock}><Plus size={12}/></button></div><div style={{ textAlign: "right" }}><strong>{money(item.price * item.quantity)}</strong><button className="small-button" onClick={() => remove(item.variantId)} style={{ display: "flex", gap: 5, marginTop: 8, marginLeft: "auto" }}><Trash2 size={12}/> Remove</button></div></div>)}</section><aside className="summary-card"><h2 style={{ margin: "0 0 12px" }}>Order summary</h2><div className="summary-line"><span>Items</span><strong>{money(subtotal)}</strong></div><div className="summary-line"><span>Tax included</span><span>Calculated on order</span></div><div className="summary-line total"><span>Estimated total</span><span>{money(subtotal)}</span></div><p className="tax-hint">GST is included in the listed product prices.</p><Link className="button" href="/checkout" style={{ width: "100%", marginTop: 14 }}>Continue to checkout <ArrowRight size={15}/></Link></aside></div>}</main>;
}
